#############################################################################
# Makefile for building: Gold_Enterprise_Sprite.app/Contents/MacOS/Gold_Enterprise_Sprite
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Gold_Enterprise_Sprite.pro
# Template: app
# Command: /Users/stephenreese/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gold_Enterprise_Sprite.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/stephenreese/Qt/5.7/clang_64/lib
QMAKE         = /Users/stephenreese/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Gold_Enterprise_Sprite1.0.0
DISTDIR = /Users/stephenreese/Desktop/Pixel/cs3505-a7-sprite-editor-gold-enterprise/.tmp/Gold_Enterprise_Sprite1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/stephenreese/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/stephenreese/Qt/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		project.cpp \
		slideview.cpp \
		gifpopup.cpp \
		newprojectdialog.cpp \
		previewdialog.cpp moc_mainwindow.cpp \
		moc_slideview.cpp \
		moc_gifpopup.cpp \
		moc_newprojectdialog.cpp \
		moc_previewdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		project.o \
		slideview.o \
		gifpopup.o \
		newprojectdialog.o \
		previewdialog.o \
		moc_mainwindow.o \
		moc_slideview.o \
		moc_gifpopup.o \
		moc_newprojectdialog.o \
		moc_previewdialog.o
DIST          = ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Gold_Enterprise_Sprite.pro mainwindow.h \
		project.h \
		slideview.h \
		gifpopup.h \
		gif.h \
		newprojectdialog.h \
		previewdialog.h main.cpp \
		mainwindow.cpp \
		project.cpp \
		slideview.cpp \
		gifpopup.cpp \
		newprojectdialog.cpp \
		previewdialog.cpp
QMAKE_TARGET  = Gold_Enterprise_Sprite
DESTDIR       = 
TARGET        = Gold_Enterprise_Sprite.app/Contents/MacOS/Gold_Enterprise_Sprite


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_gifpopup.h ui_newprojectdialog.h ui_previewdialog.h $(OBJECTS)  
	@test -d Gold_Enterprise_Sprite.app/Contents/MacOS/ || mkdir -p Gold_Enterprise_Sprite.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gold_Enterprise_Sprite.pro ../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Gold_Enterprise_Sprite.pro \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gold_Enterprise_Sprite.pro
../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
Gold_Enterprise_Sprite.pro:
../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gold_Enterprise_Sprite.pro

qmake_all: FORCE

Gold_Enterprise_Sprite.app/Contents/PkgInfo: 
	@test -d Gold_Enterprise_Sprite.app/Contents || mkdir -p Gold_Enterprise_Sprite.app/Contents
	@$(DEL_FILE) Gold_Enterprise_Sprite.app/Contents/PkgInfo
	@echo "APPL????" > Gold_Enterprise_Sprite.app/Contents/PkgInfo
Gold_Enterprise_Sprite.app/Contents/Resources/empty.lproj: 
	@test -d Gold_Enterprise_Sprite.app/Contents/Resources || mkdir -p Gold_Enterprise_Sprite.app/Contents/Resources
	@touch Gold_Enterprise_Sprite.app/Contents/Resources/empty.lproj
	
Gold_Enterprise_Sprite.app/Contents/Info.plist: 
	@test -d Gold_Enterprise_Sprite.app/Contents || mkdir -p Gold_Enterprise_Sprite.app/Contents
	@$(DEL_FILE) Gold_Enterprise_Sprite.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Gold-Enterprise-Sprite,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Gold_Enterprise_Sprite,g" -e "s,@LIBRARY@,Gold_Enterprise_Sprite,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Gold_Enterprise_Sprite.app/Contents/Info.plist

all: Makefile \
		Gold_Enterprise_Sprite.app/Contents/PkgInfo \
		Gold_Enterprise_Sprite.app/Contents/Resources/empty.lproj \
		Gold_Enterprise_Sprite.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h project.h slideview.h gifpopup.h gif.h newprojectdialog.h previewdialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp project.cpp slideview.cpp gifpopup.cpp newprojectdialog.cpp previewdialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui gifpopup.ui newprojectdialog.ui previewdialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Gold_Enterprise_Sprite.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_slideview.cpp moc_gifpopup.cpp moc_newprojectdialog.cpp moc_previewdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_slideview.cpp moc_gifpopup.cpp moc_newprojectdialog.cpp moc_previewdialog.cpp
moc_mainwindow.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		project.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QAction \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		slideview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		gifpopup.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		newprojectdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		previewdialog.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		mainwindow.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/stephenreese/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/stephenreese/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/stephenreese/Desktop/Pixel/cs3505-a7-sprite-editor-gold-enterprise -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)' -F/Users/stephenreese/Qt/5.7/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_slideview.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		slideview.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/stephenreese/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/stephenreese/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/stephenreese/Desktop/Pixel/cs3505-a7-sprite-editor-gold-enterprise -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)' -F/Users/stephenreese/Qt/5.7/clang_64/lib slideview.h -o moc_slideview.cpp

moc_gifpopup.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		gifpopup.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/stephenreese/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/stephenreese/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/stephenreese/Desktop/Pixel/cs3505-a7-sprite-editor-gold-enterprise -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)' -F/Users/stephenreese/Qt/5.7/clang_64/lib gifpopup.h -o moc_gifpopup.cpp

moc_newprojectdialog.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		newprojectdialog.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/stephenreese/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/stephenreese/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/stephenreese/Desktop/Pixel/cs3505-a7-sprite-editor-gold-enterprise -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)' -F/Users/stephenreese/Qt/5.7/clang_64/lib newprojectdialog.h -o moc_newprojectdialog.cpp

moc_previewdialog.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		previewdialog.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/stephenreese/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/stephenreese/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/stephenreese/Desktop/Pixel/cs3505-a7-sprite-editor-gold-enterprise -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/stephenreese/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)' -F/Users/stephenreese/Qt/5.7/clang_64/lib previewdialog.h -o moc_previewdialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_gifpopup.h ui_newprojectdialog.h ui_previewdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_gifpopup.h ui_newprojectdialog.h ui_previewdialog.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/stephenreese/Qt/5.7/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_gifpopup.h: gifpopup.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/stephenreese/Qt/5.7/clang_64/bin/uic gifpopup.ui -o ui_gifpopup.h

ui_newprojectdialog.h: newprojectdialog.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/stephenreese/Qt/5.7/clang_64/bin/uic newprojectdialog.ui -o ui_newprojectdialog.h

ui_previewdialog.h: previewdialog.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/stephenreese/Qt/5.7/clang_64/bin/uic previewdialog.ui -o ui_previewdialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		project.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QAction \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		slideview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		gifpopup.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		newprojectdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		previewdialog.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		project.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QAction \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		slideview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		gifpopup.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		newprojectdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		previewdialog.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		ui_mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

project.o: project.cpp project.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QAction \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		slideview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		gif.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o project.o project.cpp

slideview.o: slideview.cpp slideview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slideview.o slideview.cpp

gifpopup.o: gifpopup.cpp gifpopup.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_gifpopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gifpopup.o gifpopup.cpp

newprojectdialog.o: newprojectdialog.cpp newprojectdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_newprojectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newprojectdialog.o newprojectdialog.cpp

previewdialog.o: previewdialog.cpp previewdialog.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		ui_previewdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o previewdialog.o previewdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_slideview.o: moc_slideview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_slideview.o moc_slideview.cpp

moc_gifpopup.o: moc_gifpopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gifpopup.o moc_gifpopup.cpp

moc_newprojectdialog.o: moc_newprojectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newprojectdialog.o moc_newprojectdialog.cpp

moc_previewdialog.o: moc_previewdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_previewdialog.o moc_previewdialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

