#############################################################################
<<<<<<< HEAD
# Makefile for building: Gold_Enterprise_Sprite.app/Contents/MacOS/Gold_Enterprise_Sprite
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Gold_Enterprise_Sprite.pro
# Template: app
# Command: /Users/stephenreese/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gold_Enterprise_Sprite.pro
=======
# Makefile for building: Gold_Enterprise_Sprite
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Gold_Enterprise_Sprite.pro
# Template: app
# Command: C:\Qt\5.7\msvc2015_64\bin\qmake.exe -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Gold_Enterprise_Sprite.pro
>>>>>>> origin/master
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/stephenreese/Qt/5.7/clang_64/lib
QMAKE         = /Users/stephenreese/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Gold_Enterprise_Sprite1.0.0
DISTDIR = /Users/stephenreese/Desktop/Pixel/cs3505-a7-sprite-editor-gold-enterprise/.tmp/Gold_Enterprise_Sprite1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/stephenreese/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/stephenreese/Qt/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		project.cpp \
		slideview.cpp \
		gifpopup.cpp \
		newprojectdialog.cpp \
		previewdialog.cpp moc_mainwindow.cpp \
		moc_slideview.cpp \
		moc_gifpopup.cpp \
		moc_newprojectdialog.cpp \
		moc_previewdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		project.o \
		slideview.o \
		gifpopup.o \
		newprojectdialog.o \
		previewdialog.o \
		moc_mainwindow.o \
		moc_slideview.o \
		moc_gifpopup.o \
		moc_newprojectdialog.o \
		moc_previewdialog.o
DIST          = ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Gold_Enterprise_Sprite.pro mainwindow.h \
		project.h \
		slideview.h \
		gifpopup.h \
		gif.h \
		newprojectdialog.h \
		previewdialog.h main.cpp \
		mainwindow.cpp \
		project.cpp \
		slideview.cpp \
		gifpopup.cpp \
		newprojectdialog.cpp \
		previewdialog.cpp
QMAKE_TARGET  = Gold_Enterprise_Sprite
DESTDIR       = 
TARGET        = Gold_Enterprise_Sprite.app/Contents/MacOS/Gold_Enterprise_Sprite


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_gifpopup.h ui_newprojectdialog.h ui_previewdialog.h $(OBJECTS)  
	@test -d Gold_Enterprise_Sprite.app/Contents/MacOS/ || mkdir -p Gold_Enterprise_Sprite.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gold_Enterprise_Sprite.pro ../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Gold_Enterprise_Sprite.pro \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gold_Enterprise_Sprite.pro
../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
Gold_Enterprise_Sprite.pro:
../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gold_Enterprise_Sprite.pro

qmake_all: FORCE

Gold_Enterprise_Sprite.app/Contents/PkgInfo: 
	@test -d Gold_Enterprise_Sprite.app/Contents || mkdir -p Gold_Enterprise_Sprite.app/Contents
	@$(DEL_FILE) Gold_Enterprise_Sprite.app/Contents/PkgInfo
	@echo "APPL????" > Gold_Enterprise_Sprite.app/Contents/PkgInfo
Gold_Enterprise_Sprite.app/Contents/Resources/empty.lproj: 
	@test -d Gold_Enterprise_Sprite.app/Contents/Resources || mkdir -p Gold_Enterprise_Sprite.app/Contents/Resources
	@touch Gold_Enterprise_Sprite.app/Contents/Resources/empty.lproj
	
Gold_Enterprise_Sprite.app/Contents/Info.plist: 
	@test -d Gold_Enterprise_Sprite.app/Contents || mkdir -p Gold_Enterprise_Sprite.app/Contents
	@$(DEL_FILE) Gold_Enterprise_Sprite.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Gold-Enterprise-Sprite,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Gold_Enterprise_Sprite,g" -e "s,@LIBRARY@,Gold_Enterprise_Sprite,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Gold_Enterprise_Sprite.app/Contents/Info.plist

all: Makefile \
		Gold_Enterprise_Sprite.app/Contents/PkgInfo \
		Gold_Enterprise_Sprite.app/Contents/Resources/empty.lproj \
		Gold_Enterprise_Sprite.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h project.h slideview.h gifpopup.h gif.h newprojectdialog.h previewdialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp project.cpp slideview.cpp gifpopup.cpp newprojectdialog.cpp previewdialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui gifpopup.ui newprojectdialog.ui previewdialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Gold_Enterprise_Sprite.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
=======
first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\Qt\5.7\msvc2015_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: Gold_Enterprise_Sprite.pro C:\Qt\5.7\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf C:\Qt\5.7\msvc2015_64\mkspecs\features\spec_pre.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\common\angle.conf \
		C:\Qt\5.7\msvc2015_64\mkspecs\common\msvc-base.conf \
		C:\Qt\5.7\msvc2015_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\5.7\msvc2015_64\mkspecs\qconfig.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_purchasing.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\qt_functions.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\qt_config.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\qt_config.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\default_pre.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\resolve_config.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\default_post.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\qml_debug.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\rtti.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\precompile_header.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\warn_on.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\qt.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\resources.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\moc.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\opengl.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\uic.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\file_copies.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\windows.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\exceptions.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\yacc.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\lex.prf \
		Gold_Enterprise_Sprite.pro \
		C:\Qt\5.7\msvc2015_64\lib\qtmaind.prl \
		C:\Qt\5.7\msvc2015_64\lib\Qt5Widgets.prl \
		C:\Qt\5.7\msvc2015_64\lib\Qt5Gui.prl \
		C:\Qt\5.7\msvc2015_64\lib\Qt5Core.prl
	$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Gold_Enterprise_Sprite.pro
C:\Qt\5.7\msvc2015_64\mkspecs\features\spec_pre.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\common\angle.conf:
C:\Qt\5.7\msvc2015_64\mkspecs\common\msvc-base.conf:
C:\Qt\5.7\msvc2015_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\5.7\msvc2015_64\mkspecs\qconfig.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_purchasing.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\features\qt_functions.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\qt_config.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\qt_config.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\5.7\msvc2015_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\default_pre.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\resolve_config.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\default_post.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\qml_debug.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\rtti.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\precompile_header.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\warn_on.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\qt.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\resources.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\moc.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\opengl.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\uic.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\file_copies.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\windows.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\testcase_targets.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\exceptions.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\yacc.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\lex.prf:
Gold_Enterprise_Sprite.pro:
C:\Qt\5.7\msvc2015_64\lib\qtmaind.prl:
C:\Qt\5.7\msvc2015_64\lib\Qt5Widgets.prl:
C:\Qt\5.7\msvc2015_64\lib\Qt5Gui.prl:
C:\Qt\5.7\msvc2015_64\lib\Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Gold_Enterprise_Sprite.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) Gold_Enterprise_Sprite.exp
	-$(DEL_FILE) Gold_Enterprise_Sprite.ilk
	-$(DEL_FILE) Gold_Enterprise_Sprite.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash Gold_Enterprise_Sprite.lib Gold_Enterprise_Sprite.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
